sudo: required
services:
  - docker

before_install:
  - docker build -t kanorpokpok/docker-react -f Dockerfile.dev .

script:
  - docker run kanorpokpok/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker"
  env: "Docker-env"
  bucket-name: "elasticbeanstalk-ap-southeast-1-552341532671"
  bucket-path: "docker"
  on:
    branch: master
  accexx_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"